### ISSUE TITLE
Add possibility to override tolerations of node-agent

### ISSUE THREAD

**Issue by rufusnufus** [coroot/helm-charts#31]
We want to deploy node-agent pods only on nodes that have specific labels. Now there is no possibility - https://github.com/coroot/helm-charts/blob/d1a0cf44ee7ab6276cd0daeb9f59a50174fe4787/charts/node-agent/templates/daemonset.yaml#L32-L33
As an example:
```yaml
tolerations:
  - key: node_type
    operator: Exists
    effect: NoSchedule
```
