### ISSUE TITLE
How to configure opentelemetry-collector

### ISSUE THREAD

**Issue by l-rossetti** [coroot/helm-charts#36]
Hello,

I really appreciate coroot CE and its straightforward installation by using Helm.

I have installed opentelemetry-collector and configured it with the suggested options I see in coroot "traces" tab, but even after that the traces tab doesn't show anything and says "This page only shows traces from OpenTelemetry integrations, not from eBPF. Integrate OpenTelemetry".
What am I missing? Do I need to enable anything on coroot side? Thanks

Otel-collector values:
```
mode: daemonset
image:
  repository: otel/opentelemetry-collector-k8s

presets:
  # enables the k8sattributesprocessor and adds it to the traces, metrics, and logs pipelines
  kubernetesAttributes:
    enabled: true
  # enables the kubeletstatsreceiver and adds it to the metrics pipelines
  kubeletMetrics:
    enabled: true
  # Enables the filelogreceiver and adds it to the logs pipelines
  logsCollection:
    enabled: true

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 250m
    memory: 256Mi

###############
# Partially taken from coroot "Traces" tab
config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  processors:
    batch: {}
    # Default memory limiter configuration for the collector based on k8s resource limits.
    memory_limiter:
      # check_interval is the time between measurements of memory usage.
      check_interval: 5s
      # By default limit_mib is set to 80% of ".Values.resources.limits.memory"
      limit_percentage: 80
      # By default spike_limit_mib is set to 25% of ".Values.resources.limits.memory"
      spike_limit_percentage: 25

  exporters:
    otlphttp/coroot:
      endpoint: "http://coroot:8080"
      encoding: proto
      headers:
        "x-api-key": "9zc3qeyw"

  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch, memory_limiter]
        exporters: [otlphttp/coroot]
      logs:
        receivers: [otlp]
        processors: [batch, memory_limiter]
        exporters: [otlphttp/coroot]
```
