### ISSUE TITLE
Inconvenient coroot ingress helm chart settings

### ISSUE THREAD

**Issue by gecube** [coroot/helm-charts#37]
Good day Sirs!

I am again demonstrating coroot to my customers explaining them that it is a good solution. To do it I prepared FluxCD manifests. Everything fine for the exception that Coroot CE does not look like a thing that could be installed in one go. Let's say as a DevOps I want to publish coroot outside to be accessible by users. I need to set up ingress to do it. And what do I see? Completely different semantics than I'm used to see before.

I see the next default values:

```
  ingress:
    enabled: false
    className: ""
    hostname:
    path: /
    pathType: ImplementationSpecific
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts: []
    #  - host: chart-example.local
    #    paths:
    #      - path: /
    #        pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
```

so I am just filling hostname and hosts (no idea why, because charts of other application use this semantics) and.... nothing.

I think it would be great to change templates and values to the next as project is on early stage of development and in future it would be much harder to do it:

```
   ingress: # GOOD!
    enabled: false # GOOD!
    # className: "" # change to ingressClassName
    ingressClassName: ""
    # hostname: # throwing away
    # path: / # throwing away
    # pathType: ImplementationSpecific # throwing away
    annotations: {} # GOOD!
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts: [] # GOOD!
    #  - host: chart-example.local
    #    paths:
    #      - path: /
    #        pathType: ImplementationSpecific
    tls: [] # GOOD!
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
```

so main changes are
-  remove `className` in favour of `ingressClassName`. The logic behind it that there is no `className` field in Ingress spec and many charts use `ingressClassName` (examples: [sentry](https://github.com/sentry-kubernetes/charts/blob/b2f568d926771208256d47f03a2f39806ca94fe3/charts/sentry/values.yaml#L1775), [nixys universal chart](https://github.com/nixys/nxs-universal-chart/blob/a6e4731cd2c88f8c9512cd459fb1cde911fc11bd/templates/ingress.yml#L26), [victoria stack](https://github.com/VictoriaMetrics/helm-charts/blob/563182dbcf312e1fc57f01735c0dcb92691194f3/charts/victoria-metrics-k8s-stack/values.yaml#L289)). It is clear and standard. I don't think that it is good to be different
- remove dedicated `hostname`/`path`/`pathType` keys. If user of the chart wants, it would be easy to him to populate `hosts` lists like it is done in other charts. Now the two settings creates confusion. I may guess that authors of the coroot chart thought that user may want to add additional hosts to the default one. But in fact managing of single list is simpler.
