### ISSUE TITLE
Prometheus Version very old

### ISSUE THREAD

**Issue by alamos-gmbh** [coroot/helm-charts#38]
The prometheus version bundled with the chart is rather old.
So old, that using the coroot prometheus as a cluster wide prometheus instance, leads to issues while scraping spring boot actuator prometheus. manually changing the prometheus image version to e.g. 
```
prometheus:
  server:
     image:
       tag: "v2.45.0"
```
works. But images like configmap-reload docker.io/jimmidyson/configmap-reload:v0.5.0 stay old of course.

Could you possibly upgrade to a newer version of the prometheus service?
