### ISSUE TITLE
Unable to Customize Images of Components (e.g., Node Agent) in coroot-operator Helm Chart

### ISSUE THREAD

**Issue by Mehdi-BR** [coroot/helm-charts#46]
I am trying to deploy the coroot-operator using the Helm chart, and I need to customize the images for all components to pull them from my private container registry. However, I have only found a way to specify the image for the operator itself (coroot-operator) (via the values.yaml file) and not for other components.
please help

**Comment by apetruhin** [comment]
Coroot Operation v1.2.0 introduced the `image` option to specify a private registry for component images.
Now you can configure [Coroot Custom Resource](https://docs.coroot.com/installation/k8s-operator) to pull images from your private registry:
```yaml
communityEdition:
  image:
    name: <private-registry>/coroot:<version>
nodeAgent:
  image:
    name: <private-registry>/coroot-node-agent:<version>
clusterAgent:
  image:
    name: <private-registry>/coroot-cluster-agent:<version>
...
```
